//@version=6
indicator(title = "Custom Session VWAP", shorttitle = "CVWAP", overlay = true)

float source = input.source(hlc3, "Source", tooltip="", inline="", group="Volume Weighted Average Price")
string my_session = input.session("0830-1600", title='Custom Session')

timeinrange(res, sess) => not na(time(res, sess))

in_session = timeinrange("1", my_session)

newYorkVwap = ta.vwap(source, in_session[0] and not in_session[1])

plotNewYorkVwap = plot(in_session ? newYorkVwap  : na, "Custom Session VWAP", color.orange, 1, plot.style_linebr, false, 0, 0)